### ISSUE TITLE
should be rpc :)

### ISSUE THREAD

**Issue by CryptoGrampy** [nahuhh/android-termux-monero-node#14]
https://github.com/nahuhh/android-termux-monero-node/blob/3a6d8577c81d153dc249550eb80ddbef9372bca8/src/install-monerod-in-termux.sh#L197

**Comment by nahuhh** [comment]
Fix: https://github.com/nahuhh/android-termux-monero-node/commit/203cabfe5530df3d13f2ba47e28b8c60c236d60c

Update: https://github.com/nahuhh/android-termux-monero-node/commit/c721198e04967a21892ba3ea4e0c54a494c8d8b3
a couple more fixes for https self signed cert


Tyty

~~Fixed and reuploaded 4.1
https://github.com/nahuhh/android-termux-monero-node/releases/tag/v4.1.0~~

If all is working well on your end, ill push to main and open PR

**Comment by CryptoGrampy** [comment]
Running really well.  Had some of those weird Termux setup storage issues, so uninstalled it with all of the addons and reinstalled/updated everything.  Working great now.

**Comment by CryptoGrampy** [comment]
Any interest in building out a Monerod package for Yunohost?  It's mostly bash based and we've probably done a decent amount of the work so far. 

https://yunohost.org/
https://yunohost.org/en/packaging_apps
https://github.com/YunoHost/example_ynh
https://github.com/YunoHost-Apps/helloworld_ynh

**Comment by nahuhh** [comment]
Going to default the SSL flag for now. Was having issues connecting from wan 

https://github.com/monero-project/monero/issues/7482#issuecomment-801093054

https://github.com/monero-project/monero/issues/6262

https://github.com/monero-project/monero/issues/6262#issuecomment-855344735

**Comment by nahuhh** [comment]
@CryptoGrampy 
Hey
I did a bit of condensing and reorg of the readme.

Im going to push 4.1.1 install to main, but was wondering if if youd be ok with me pushing the updated readme as well?

https://github.com/nahuhh/android-termux-monero-node/blob/4.1.1/README.md

https://github.com/nahuhh/android-termux-monero-node/releases/tag/V4.1.1

**Comment by CryptoGrampy** [comment]
Looks great to me.

**Comment by nahuhh** [comment]
Done

**Comment by nahuhh** [comment]
> Running really well. Had some of those weird Termux setup storage issues, so uninstalled it with all of the addons and reinstalled/updated everything. Working great now.

The next time you update can you select N when it asks about setting up termux folders. 

Im thinking the issue might be subsequent runs on the command are breaking it. In which case, I can add an arguement to check to see if the folders already exist, and if so, not to run the storage setup command again.

--- or is it random? Losing access after reboot etc? Or only after upgrading?
